Repository Codeit-Rolling-11-Letsgo/Rolling, pull requests merged in 2023-12, with the labels that each got.

#4 style: 폰트, 컬러 변수 지정
  src/assets/variables.scss
  src/pages/home/HomePage.module.scss
  vite.config.js
Labels: feature

#6 Create pull_request_template.md
  pull_request_template.md
Labels: docs

#10 Fix: :root가 아닌 #root에 폰트 사이즈 작성한 것을 수정
  src/assets/globals.scss
Labels: fix

#11 공통 컴포넌트 추가(아이콘, 레이아웃)
  .gitignore
  index.html
  src/apis/icon/iconAPI.js
  src/assets/globals.scss
  src/assets/reset.scss
  src/assets/utilities.scss
  src/assets/variables.scss
  src/components/common/Layout.jsx
  src/components/common/Layout.module.scss
  src/components/common/icon/Icon.jsx
  src/components/common/icon/Icon.module.scss
  src/components/common/icon/ImageIcon.jsx
  src/components/common/icon/SVGIcon.jsx
  src/queries/useIconQuery.js
Labels: feature

#18 Feat: 홈페이지 레이아웃 구현
  src/assets/globals.scss
  src/assets/variables.scss
  src/components/common/Layout.jsx
  src/components/common/Layout.module.scss
  src/components/home/HomeLayout.jsx
  src/components/home/HomeLayout.module.scss
  src/pages/home/HomePage.jsx
Labels: feature

#15 feat: DropDown 컴포넌트 제작
  src/components/common/DropDown/DropDown.jsx
  src/components/common/DropDown/DropDown.module.scss
Labels: feature

#20 Feat: 홈페이지 메인 컨텐츠 구현
  src/components/common/Image.jsx
  src/components/common/Layout.module.scss
  src/components/common/card/Card.jsx
  src/components/common/card/CardDescription.jsx
  src/components/common/card/CardPanel.jsx
  src/components/common/card/CardThumbnail.jsx
  src/components/common/card/CardTitle.jsx
  src/components/home/HomeLayout.module.scss
  src/pages/home/HomePage.jsx
  src/pages/home/HomePage.module.scss
Labels: feature

#29 Feat: 공통 api fetcher 추가
  src/apis/CustomHTTPError.js
  src/apis/fetcher.js
Labels: feature

#27 feat: EmojiPickerButton 컴포넌트 제작
  package-lock.json
  package.json
  src/components/HeaderService/EmojiPickerButton.jsx
  src/components/HeaderService/EmojiPickerButton.module.scss
Labels: feature

#34 Feat: post 페이지 기본 구현
  src/apis/post/postAPI.js
  src/components/post/NewMessageCTA.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostCard.module.scss
  src/components/post/PostLayout.jsx
  src/components/post/PostLayout.module.scss
  src/main.jsx
  src/pages/post/PostPage.jsx
  src/pages/post/PostPage.module.scss
  src/utils/dateFunc.js
Labels: feature

#31 feat: 이모지 post request 작업
  src/apis/recipients/reactionsAPI.js
  src/components/HeaderService/EmojiPickerButton.jsx
  src/components/HeaderService/EmojiPickerButton.module.scss
Labels: feature

#36 feat: 이모지바 url공유 기능 제작
  src/components/HeaderService/ShareButton.jsx
  src/components/HeaderService/ShareButton.module.scss
Labels: feature

#25 feat: 이모지바 레이아웃 구현
  src/components/HeaderService/HeaderService.jsx
  src/components/HeaderService/HeaderService.module.scss
Labels: feature

#41 refactor: header-service 폴더 post 폴더내로 이동
  src/components/post/header-service/EmojiPickerButton.jsx
  src/components/post/header-service/EmojiPickerButton.module.scss
  src/components/post/header-service/HeaderService.jsx
  src/components/post/header-service/HeaderService.module.scss
  src/components/post/header-service/ShareButton.jsx
  src/components/post/header-service/ShareButton.module.scss
Labels: fix

#38 Feat: post 본문 무한 스크롤 구현
  src/apis/post/postAPI.js
  src/components/post/PostCard.jsx
  src/components/post/PostLayout.module.scss
  src/hooks/useIntersect.js
  src/main.jsx
  src/pages/post/PostIdPage.jsx
  src/pages/post/PostIdPage.module.scss
  src/pages/post/PostPage.jsx
  src/utils/dateUtils.js
Labels: feature

#45 feat: 받은 이모지 확인 드롭다운 제작 및 이모지바를 postId 페이지에 합치는 작업
  package-lock.json
  package.json
  src/apis/recipients/reactionsAPI.js
  src/components/post/header-service/EmojiBadge.jsx
  src/components/post/header-service/EmojiBadge.module.scss
  src/components/post/header-service/EmojiPickerButton.jsx
  src/components/post/header-service/EmojiPickerButton.module.scss
  src/components/post/header-service/EmojiReactionCollection.jsx
  src/components/post/header-service/EmojiReactionCollection.module.scss
  src/components/post/header-service/EmojiReactionViewer.jsx
  src/components/post/header-service/EmojiReactionViewer.module.scss
  src/components/post/header-service/HeaderService.jsx
  src/components/post/header-service/HeaderService.module.scss
  src/components/post/header-service/ShareButton.jsx
  src/components/post/header-service/ShareButton.module.scss
  src/components/post/header-service/TopEmojiReactionList.jsx
  src/pages/post/PostIdPage.jsx
Labels: feature

#48 Fix: module export 에러 수정
  src/pages/post/PostIdPage.jsx
Labels: fix

#44 Feat: 리스트 페이지 구현(캐러셀 제외)
  src/apis/CustomHTTPError.js
  src/apis/icon/iconAPI.js
  src/apis/recipients/recipientsAPI.js
  src/assets/utilities.scss
  src/components/common/EmojiBadge.jsx
  src/components/common/EmojiBadge.module.scss
  src/components/common/card/Card.jsx
  src/components/common/card/CardSplitter.jsx
  src/components/common/icon/Icon.jsx
  src/components/common/icon/ImageIcon.jsx
  src/components/common/icon/SVGIcon.jsx
  src/components/list/ListContent.jsx
  src/components/list/ListContent.module.scss
  src/components/list/ListLayout.jsx
  src/components/list/ListLayout.module.scss
  src/components/list/RecipientCard.jsx
  src/components/list/RecipientCard.module.scss
  src/components/list/RecipientCardList.jsx
  src/components/list/RecipientCardList.module.scss
  src/hooks/common/useBackgroundImage.js
  src/main.jsx
  src/pages/list/ListPage.jsx
  src/pages/list/ListPage.module.scss
  src/queries/useIconQuery.js
  src/utils/iconUtil.js
  src/utils/util.js
Labels: feature

#53 Feature: 모달 구현
  src/apis/post/postAPI.js
  src/components/common/modal/Modal.jsx
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/ModalButtons.jsx
  src/components/common/modal/ModalContent.jsx
  src/components/common/modal/ModalTitle.jsx
  src/components/post/PostBadge.jsx
  src/components/post/PostBadge.module.scss
  src/components/post/PostCard.jsx
  src/components/post/PostCard.module.scss
  src/components/post/PostLayout.jsx
  src/components/post/PostLayout.module.scss
  src/components/post/PostModal.jsx
  src/components/post/PostModal.module.scss
  src/contexts/ModalContext.jsx
  src/hooks/useModalContext.js
  src/main.jsx
  src/pages/post/PostIdPage.jsx
  src/pages/post/PostIdPage.module.scss
Labels: feature

#52 Feat: 캐러셀 구현
  src/assets/reset.scss
  src/assets/utilities.scss
  src/assets/variables.scss
  src/components/common/carousel/Carousel.jsx
  src/components/common/carousel/Carousel.module.scss
  src/components/list/ListContent.module.scss
  src/components/list/ListLayout.module.scss
  src/components/list/RecipientCardList.jsx
  src/components/list/RecipientCardList.module.scss
Labels: feature

#58 Feat: 배경 색 or 이미지 적용 및 recipient 정보 전달
  src/apis/post/postAPI.js
  src/components/post/PostLayout.module.scss
  src/contexts/RecipientInfoContext.jsx
  src/hooks/useRecipientInfo.js
  src/main.jsx
  src/pages/post/PostIdPage.jsx
Labels: feature

#60 feat: 이모지바 레이아웃 완성
  .vscode/settings.json
  index.html
  src/assets/variables.scss
  src/components/common/Layout.module.scss
  src/components/post/header-service/EmojiPickerButton.module.scss
  src/components/post/header-service/EmojiReactionViewer.jsx
  src/components/post/header-service/EmojiReactionViewer.module.scss
  src/components/post/header-service/HeaderService.jsx
  src/components/post/header-service/HeaderService.module.scss
  src/components/post/header-service/ShareButton.jsx
  src/components/post/header-service/ShareButton.module.scss
  src/utils/kakaoShareFormatting.js
Labels: feature

#70 Fix: padding_safe_zone 이름 수정
  src/components/list/ListLayout.module.scss
Labels: fix

#74 Fix: 레이아웃 조정
  src/components/common/Layout.jsx
  src/components/common/Layout.module.scss
  src/components/common/header/GlobalHeader.jsx
  src/components/common/header/GlobalHeader.module.scss
  src/components/home/HomeLayout.jsx
  src/components/list/ListLayout.jsx
  src/components/list/ListLayout.module.scss
  src/components/post/PostLayout.jsx
  src/components/post/PostLayout.module.scss
  src/components/post/header-service/HeaderService.jsx
  src/components/post/header-service/HeaderService.module.scss
Labels: fix

#76 Fix: 홈페이지, 리스트 페이지 이슈 수정
  src/pages/home/HomePage.jsx
  src/pages/home/HomePage.module.scss
  src/pages/list/ListPage.module.scss
Labels: fix

#79 feat: postId 페이지 애니메이션 적용
  package-lock.json
  package.json
  src/components/common/EmojiBadge.module.scss
  src/components/common/modal/Modal.jsx
  src/components/post/NewMessageCTA.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostCard.module.scss
  src/components/post/header-service/EmojiBadge.jsx
  src/components/post/header-service/EmojiBadge.module.scss
  src/components/post/header-service/EmojiPickerButton.jsx
  src/components/post/header-service/EmojiReactionCollection.jsx
  src/components/post/header-service/ShareButton.jsx
  src/components/post/header-service/ShareButton.module.scss
  src/components/post/header-service/TopEmojiReactionList.jsx
  src/utils/framerAnimation.js
Labels: feature

#66 Feat: post 페이지 edit 상태 구현
  src/apis/post/postAPI.js
  src/components/post/PostCard.jsx
  src/components/post/PostCard.module.scss
  src/components/post/PostModal.jsx
  src/contexts/RecipientInfoContext.jsx
  src/hooks/useRecipientInfo.js
  src/main.jsx
  src/pages/post/PostIdPage.jsx
  src/pages/post/PostIdPage.module.scss
Labels: feature

#80 Feature: 모달 외부 스크롤 방지, 외부 클릭 시 닫힘
  src/components/common/modal/Modal.jsx
Labels: feature

#62 post, postMessage 페이지 구현
  .vscode/settings.json
  package-lock.json
  package.json
  src/apis/post/postRecipients.js
  src/apis/post/postRecipientsMessage.js
  src/components/common/Buttons/Button.jsx
  src/components/common/Buttons/Button.scss
  src/main.jsx
  src/pages/PostIdMessage/FontSelect.jsx
  src/pages/PostIdMessage/FontSelect.scss
  src/pages/PostIdMessage/PostMessage.jsx
  src/pages/PostIdMessage/PostMessage.scss
  src/pages/PostIdMessage/ProfileImageSelect.jsx
  src/pages/PostIdMessage/ProfileImageSelect.scss
  src/pages/PostIdMessage/TextEditor.jsx
  src/pages/PostIdMessage/TextEditor.scss
  src/pages/post/PostPage.jsx
  src/pages/post/PostPage.scss
  src/pages/post/Select.jsx
  src/pages/post/Select.scss
  src/pages/post/SelectItem.jsx
Labels: feature

#82 Style: 모든 반응형 미디어쿼리 공통 mixin 으로 변경
  src/assets/variables.scss
  src/components/common/EmojiBadge.module.scss
  src/components/common/carousel/Carousel.module.scss
  src/components/list/ListLayout.module.scss
  src/components/list/RecipientCard.module.scss
  src/components/post/PostBadge.module.scss
  src/components/post/PostCard.module.scss
  src/components/post/PostLayout.module.scss
  src/components/post/PostModal.module.scss
  src/components/post/header-service/EmojiPickerButton.module.scss
  src/components/post/header-service/EmojiReactionCollection.module.scss
  src/components/post/header-service/EmojiReactionViewer.module.scss
  src/components/post/header-service/HeaderService.jsx
  src/components/post/header-service/HeaderService.module.scss
  src/components/post/header-service/ShareButton.module.scss
  src/pages/list/ListPage.module.scss
  src/pages/post/PostIdPage.module.scss
Labels: fix

#83 Feat: 캐러셀 크기에 따라 넘어가는 아이템 수 변경
  src/components/common/carousel/Carousel.jsx
  src/components/list/RecipientCardList.jsx
  src/hooks/common/useDOMWidth.js
  src/utils/util.js
Labels: feature

#12 공통 컴포넌트 추가 (버튼)
  src/components/common/button/Button.jsx
  src/components/common/button/Button.module.scss
Labels: feature

#87 feat: 사용자 경험 개선
  src/components/common/DropDown/DropDown.jsx
  src/components/common/DropDown/DropDown.module.scss
  src/components/list/RecipientCard.jsx
  src/pages/PostIdMessage/PostMessage.jsx
  src/utils/framerAnimation.js
Labels: feature

#88 Feat: post id edit 페이지 반응형 구현
  src/components/post/NewMessageCTA.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostCard.module.scss
  src/components/post/PostModal.jsx
  src/pages/post/PostIdPage.jsx
  src/pages/post/PostIdPage.module.scss
Labels: feature

#90 Feat: post card, modal에 한해 ol, ul 스타일 되살리기
  src/components/post/PostCard.module.scss
  src/components/post/PostModal.module.scss
Labels: feature

#96 fix: Toast 여러번 클릭해도 동일한 timer 공유하는 버그 수정
  src/components/post/header-service/ShareButton.jsx
Labels: fix

#100 fix: 자잘한 버그 수정
  src/components/common/EmojiBadge.module.scss
  src/components/post/header-service/EmojiPickerButton.jsx
  src/components/post/header-service/EmojiPickerButton.module.scss
Labels: fix

#98 Feature: Post 페이지, PostMessage 페이지 반응형 구현
  src/components/common/Buttons/Button.jsx
  src/components/common/Buttons/Button.scss
  src/components/common/button/ToggleButton.jsx
  src/pages/PostIdMessage/PostMessage.jsx
  src/pages/PostIdMessage/PostMessage.scss
  src/pages/PostIdMessage/ProfileImageSelect.jsx
  src/pages/PostIdMessage/ProfileImageSelect.scss
  src/pages/PostIdMessage/TextEditor.scss
  src/pages/post/PostPage.jsx
  src/pages/post/PostPage.scss
  src/pages/post/Select.jsx
  src/pages/post/Select.scss
Labels: feature

#104 fix: 버튼 컴포넌트 공통 컴포넌트 교체로 인한 스타일 버그들 수정
  src/components/common/button/Button.jsx
  src/components/common/button/Button.module.scss
  src/components/post/PostLayout.module.scss
  src/components/post/header-service/EmojiPickerButton.jsx
  src/pages/post/PostIdPage.jsx
  src/pages/post/PostIdPage.module.scss
Labels: fix

#106 Feat: 모바일 화면 모달 크기 조정
  src/components/common/modal/Modal.module.scss
  src/components/post/PostCard.module.scss
  src/components/post/PostModal.module.scss
Labels: feature

#105 Feature/d0ngbb00/101
  src/pages/PostIdMessage/FontSelect.jsx
  src/pages/PostIdMessage/FontSelect.module.scss
  src/pages/PostIdMessage/FontSelect.scss
  src/pages/PostIdMessage/PostMessage.jsx
  src/pages/PostIdMessage/PostMessage.module.scss
  src/pages/PostIdMessage/ProfileImageSelect.jsx
  src/pages/PostIdMessage/ProfileImageSelect.module.scss
  src/pages/PostIdMessage/TextEditor.jsx
  src/pages/PostIdMessage/TextEditor.module.scss
  src/pages/post/PostPage.jsx
  src/pages/post/PostPage.module.scss
  src/pages/post/Select.jsx
  src/pages/post/Select.module.scss
  src/pages/post/Select.scss
  src/pages/post/SelectItem.jsx
Labels: feature

#108 feat: favicon 추가
  index.html
Labels: feature

#110 Feat: 홈페이지, 리스트 페이지 cta width 조절
  src/pages/home/HomePage.jsx
  src/pages/list/ListPage.jsx
Labels: feature

#112 Fix: 토글 버튼 type 수정
  src/components/common/button/ToggleButton.jsx
Labels: fix

#115 Fix: 이모지 리액션 버튼 중간 정렬
  src/assets/reset.scss
  src/components/post/header-service/EmojiReactionCollection.jsx
  src/components/post/header-service/EmojiReactionCollection.module.scss
Labels: fix

#118 Feat: 필요한 폰트 미리 추가
  src/assets/globals.scss
  src/components/post/PostCard.jsx
  src/components/post/PostModal.jsx
  src/constants/fontNames.js
Labels: feature

#120 Fix: 모바일 환경에서 카드 클릭 시 파란색 배경 들어가는 기능 제거
  src/assets/reset.scss
Labels: fix
